-- USER 테이블 드롭
DROP TABLE IF EXISTS SLEEP_USER_T;
DROP TABLE IF EXISTS LEAVE_USER_T;
DROP TABLE IF EXISTS USER_ACCESS_T;
DROP TABLE IF EXISTS USER_T;

-- 회원 USER
CREATE TABLE USER_T (
    USER_NO        INT AUTO_INCREMENT PRIMARY KEY,
    ID             VARCHAR(40) NOT NULL UNIQUE,
    PW             VARCHAR(64) NOT NULL,
    NAME           VARCHAR(40),
    GENDER         VARCHAR(2),
    EMAIL          VARCHAR(100) NOT NULL UNIQUE,
    MOBILE         VARCHAR(15),
    BIRTHYEAR      VARCHAR(4),
    BIRTHDATE      VARCHAR(4),
    POSTCODE       VARCHAR(5),
    ROAD_ADDRESS   VARCHAR(100),
    JIBUN_ADDRESS  VARCHAR(100),
    DETAIL_ADDRESS VARCHAR(100),
    EXTRA_ADDRESS  VARCHAR(100),
    AGREECODE      INT NOT NULL,
    JOINED_AT      DATE,
    PW_MODIFIED_AT DATE,
    AUTOLOGIN_ID   VARCHAR(32),
    AUTOLOGIN_EXPIRED_AT DATE,
    SELLER_CHECK   INT
);

-- 회원 접속 기록(회원마다 마지막 로그인 날짜 1개만 기록)
CREATE TABLE USER_ACCESS_T (
    ID            VARCHAR(40) NOT NULL UNIQUE,
    LAST_LOGIN_AT DATE
);

-- 탈퇴 (탈퇴한 아이디로 재가입이 불가능)
CREATE TABLE LEAVE_USER_T (
    ID        VARCHAR(40)  NOT NULL UNIQUE,
    EMAIL     VARCHAR(100) NOT NULL UNIQUE,
    JOINED_AT DATE,
    LEAVED_AT DATE
);

-- 휴면 (1년 이상 로그인을 안하면 휴면 처리)
CREATE TABLE SLEEP_USER_T (
    USER_NO        INT NOT NULL,
    ID             VARCHAR(40) NOT NULL UNIQUE,
    PW             VARCHAR(64) NOT NULL,
    NAME           VARCHAR(40),
    GENDER         VARCHAR(2),
    EMAIL          VARCHAR(100) NOT NULL UNIQUE,
    MOBILE         VARCHAR(15),
    BIRTHYEAR      VARCHAR(4),
    BIRTHDATE      VARCHAR(4),
    POSTCODE       VARCHAR(5),
    ROAD_ADDRESS   VARCHAR(100),
    JIBUN_ADDRESS  VARCHAR(100),
    DETAIL_ADDRESS VARCHAR(100),
    EXTRA_ADDRESS  VARCHAR(100),
    AGREECODE      INT NOT NULL,
    JOINED_AT      DATE,
    PW_MODIFIED_AT DATE,
    SLEPT_AT       DATE
);